# Generated by Django 4.1 on 2022-08-04 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BertopicBuffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='human readable identifier for bertopic run request', max_length=100)),
                ('json_keyword_list', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapeBuffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='human readable identifier for scrape run request', max_length=100)),
                ('date_scraped', models.DateField()),
                ('close_spider_page_count', models.IntegerField()),
                ('css_selector', models.CharField(max_length=255)),
                ('depth_limit', models.IntegerField()),
                ('json_url_list', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ScrapeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('fk_scrape_buffer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='snbrequest.scrapebuffer')),
            ],
        ),
        migrations.CreateModel(
            name='BertopicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('json_topic_data', models.TextField()),
                ('keyword_topic_cluster', models.TextField()),
                ('fk_bert_buffer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='snbrequest.bertopicbuffer')),
                ('fk_scrape_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='snbrequest.scrapedata')),
            ],
        ),
        migrations.AddField(
            model_name='bertopicbuffer',
            name='fk_scrape_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='snbrequest.scrapedata'),
        ),
    ]
