# Generated by Django 4.1 on 2022-08-04 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snbrequest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bertopicdata',
            name='date_trained',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='scrapedata',
            name='date_scraped',
            field=models.DateField(auto_now=True),
        ),
    ]
